name: NETVEIWER
description: >
          A Demo App which does almost nothing of any practical value.
version: 0.0.1-rancher1
category: HANA
maintainer: Techwave <saikrishna.rayapati@techwave.net>
license: not-licensed
projectURL: https://www.hostlogic.hu/client_portal
